User.create(:login => "testuser", :email => "test@test.com", :password => "password", :password_confirmation => "password", :birthday => "5/6/1986")
Wisdom.create(:quote => "quote test", :user_id => 1, :submitter_age => 22, :karma => 1)
Wisdom.create(:quote => "quote test", :user_id => 1, :submitter_age => 22, :karma => 3)
Wisdom.create(:quote => "quote test", :user_id => 1, :submitter_age => 15, :karma => 4)
Wisdom.create(:quote => "quote test", :user_id => 1, :submitter_age => 22, :karma => 1)
Wisdom.create(:quote => "quote test", :user_id => 1, :submitter_age => 22, :karma => 10)
Wisdom.create(:quote => "quote test", :user_id => 1, :submitter_age => 12, :karma => 76)
Wisdom.create(:quote => "quote test", :user_id => 1, :submitter_age => 22, :karma => 23)
Wisdom.create(:quote => "quote test", :user_id => 1, :submitter_age => 22, :karma => 9)
Wisdom.create(:quote => "quote test", :user_id => 1, :submitter_age => 22, :karma => 14)
Wisdom.create(:quote => "quote test", :user_id => 1, :submitter_age => 56, :karma => 9)
Wisdom.create(:quote => "quote test", :user_id => 1, :submitter_age => 22, :karma => 10)
Wisdom.create(:quote => "quote test", :user_id => 1, :submitter_age => 22, :karma => 87)
Wisdom.create(:quote => "quote test", :user_id => 1, :submitter_age => 85, :karma => 62)
Wisdom.create(:quote => "quote test", :user_id => 1, :submitter_age => 22, :karma => 8)
Wisdom.create(:quote => "quote test", :user_id => 1, :submitter_age => 100, :karma => 82)
